export const surpriseMePrompts = [
  "A breathtaking sunset over a tranquil lake",
  "A whimsical garden filled with colorful flowers and butterflies",
  "A majestic mountain peak covered in a blanket of snow",
  "A serene beach with crystal clear turquoise water",
  "A magical forest with sunlight streaming through the trees",
  "A charming cottage surrounded by blooming cherry blossom trees",
  "A vibrant field of wildflowers in full bloom",
  "A stunning night sky filled with twinkling stars",
  "A picturesque waterfall nestled in a lush green valley",
  "An enchanting castle on top of a hill overlooking a picturesque landscape",
  "A peaceful countryside scene with rolling hills and grazing sheep",
  "A radiant rainbow stretching across the sky",
  "A cozy fireplace with crackling logs on a chilly evening",
  "A graceful ballet dancer performing on a grand stage",
  "A magnificent peacock displaying its vibrant feathers",
  "A row of colorful hot air balloons floating in the sky",
  "A tranquil garden pond with graceful koi fish swimming",
  "A cascading waterfall surrounded by lush tropical vegetation",
  "A beautifully decorated wedding cake with intricate details",
  "A sunflower field bathed in golden sunlight",
  "A panoramic view of a bustling city skyline at night",
  "A field of lavender in full bloom, emitting a soothing fragrance",
  "A majestic eagle soaring through the clear blue sky",
  "A charming European street lined with historic buildings",
  "A peaceful boat ride on a calm lake surrounded by mountains",
  "A breathtaking view of the Northern Lights dancing across the sky",
  "A picturesque vineyard with rows of lush grapevines",
  "A cozy reading nook with a comfortable armchair and bookshelf",
  "A pristine white sandy beach with turquoise waves crashing",
  "A beautiful butterfly perched delicately on a vibrant flower",
  "A colorful autumn landscape with trees ablaze in red, orange, and gold",
  "A serene yoga retreat nestled in the mountains",
  "A classic black and white photograph capturing a candid moment",
  "A charming village square with bustling cafes and shops",
  "A field of sunflowers stretching as far as the eye can see",
  "A tranquil zen garden with carefully raked sand and stone sculptures",
  "A vibrant street market filled with fresh fruits and vegetables",
  "A romantic candlelit dinner under a starry sky",
  "A majestic waterfall plunging into a deep blue pool",
  "A picturesque coastal cliff with waves crashing against the rocks",
  "A colorful hot air balloon festival in full swing",
  "A serene lakeside cabin surrounded by towering pine trees",
  "A charming vintage carousel with intricately painted horses",
  "A stunning view of a snow-capped mountain range",
  "A blooming cherry blossom tree in a peaceful garden",
  "A tranquil boat ride along a winding river",
  "A vibrant fireworks display lighting up the night sky",
  "A peaceful country road lined with blooming wildflowers",
  "A cozy log cabin nestled in a snowy mountain landscape",
  "A captivating sunset over a field of golden wheat",
];
/* export const surpriseMePrompts = [
  "an armchair in the shape of an avocado",
  "a surrealist dream-like oil painting by Salvador Dalí of a cat playing checkers",
  "teddy bears shopping for groceries in Japan, ukiyo-e",
  "an oil painting by Matisse of a humanoid robot playing chess",
  "panda mad scientist mixing sparkling chemicals, digital art",
  "a macro 35mm photograph of two mice in Hawaii, they're each wearing tiny swimsuits and are carrying tiny surf boards, digital art",
  "3D render of a cute tropical fish in an aquarium on a dark blue background, digital art",
  "an astronaut lounging in a tropical resort in space, vaporwave",
  "an oil painting portrait of a capybara wearing medieval royal robes and an ornate crown on a dark background",
  "a stained glass window depicting a hamburger and french fries",
  "a pencil and watercolor drawing of a bright city in the future with flying cars",
  "a sunlit indoor lounge area with a pool with clear water and another pool with translucent pastel pink water, next to a big window, digital art",
  "a fortune-telling shiba inu reading your fate in a giant hamburger, digital art",
  '"a sea otter with a pearl earring" by Johannes Vermeer',
  "an oil pastel drawing of an annoyed cat in a spaceship",
  "a painting of a fox in the style of Starry Night",
  "a bowl of soup that looks like a monster, knitted out of wool",
  "A plush toy robot sitting against a yellow wall",
  "A synthwave style sunset above the reflecting water of the sea, digital art",
  "Two futuristic towers with a skybridge covered in lush foliage, digital art",
  "A 3D render of a rainbow colored hot air balloon flying above a reflective lake",
  "A comic book cover of a superhero wearing headphones",
  "A centered explosion of colorful powder on a black background",
  "A photo of a Samoyed dog with its tongue out hugging a white Siamese cat",
  "A photo of a white fur monster standing in a purple room",
  "A photo of Michelangelo's sculpture of David wearing headphones djing",
  "A Samurai riding a Horse on Mars, lomography.",
  "A modern, sleek Cadillac drives along the Gardiner expressway with downtown Toronto in the background, with a lens flare, 50mm photography",
  "A realistic photograph of a young woman with blue eyes and blonde hair",
  "A man standing in front of a stargate to another dimension",
  "Spongebob Squarepants in the Blair Witch Project",
  "A velociraptor working at a hotdog stand, lomography",
  "A man walking through the bustling streets of Kowloon at night, lit by many bright neon shop signs, 50mm lens",
  "A BBQ that is alive, in the style of a Pixar animated movie",
  "A futuristic cyborg dance club, neon lights",
  "The long-lost Star Wars 1990 Japanese Anime",
  "A hamburger in the shape of a Rubik’s cube, professional food photography",
  "A Synthwave Hedgehog, Blade Runner Cyberpunk",
  "An astronaut encountering an alien life form on a distant planet, photography",
  "A Dinosaur exploring Cape Town, photography",
  "A Man falling in Love with his Computer, digital art",
  "A photograph of a cyborg exploring Tokyo at night, lomography",
  "Dracula walking down the street of New York City in the 1920s, black and white photography",
  "Synthwave aeroplane",
  "A man wanders through the rainy streets of Tokyo, with bright neon signs, 50mm",
  "A Space Shuttle flying above Cape Town, digital art",
];
 */