import React from "react";
import Modal from "react-modal";
import { AuthContext, downloadImage } from "../../utils";
import { ArrowDownTrayIcon } from "@heroicons/react/24/solid";
import { HeartIcon } from "@heroicons/react/24/outline";

const ModalImageDetail = ({ isOpen, onClose, image }) => {
  return (
    <Modal
      isOpen={isOpen}
      onRequestClose={onClose}
      className="modal modal-image" // w-3/4 max-w-[70%] !important
      overlayClassName="modal-overlay"
    >
      <button
        className="text-medium-grey font-bold absolute top-2 right-3"
        onClick={onClose}
      >
        X
      </button>

      <div className="md:flex bg-dark-blue px-4 rounded-lg">
        {/* Left Side */}
        <div className=" lg:w-1/2 pr-6 flex items-center justify-center">
          <img
            src={image.url}
            alt="AI Generated Image"
            className="rounded-md h-32 lg:h-128"
          />
        </div>

        {/* Right Side */}
        <div className="w-1/2 pl-8">
          <h2 className="text-light-grey mt-8 mb-4">
            Generated by:
            <div className="inline-flex items-center">
              <div className="w-7 h-7 ms-3 rounded-full object-cover bg-neon-pink flex justify-center items-center text-white text-xs font-bold">
                {image.user.username[0]}
              </div>
              <span className="font-bold ml-2">{image.user.username}</span>
            </div>
          </h2>
          <div className="font-extrabold text-3xl text-light-grey my-8">
            <h1>{image.prompt.substring(0, 20)}...</h1>
          </div>

          <p className=" text-light-grey font-bold mb-2">Prompt used: </p>
          <p className="text-light-grey">{image.prompt}</p>
          <div className="flex mt-12">
            <p className="bg-medium-grey text-light-grey font-semibold px-5 py-2 rounded-full mr-6 inline-flex">
              <HeartIcon
                //onClick={handleLike}
                className="h-5 w-5 me-2 text-white inline-flex"
              />{" "}
              Likes:<span className="likesNumber ms-2">{image.likes}</span>
            </p>
            <button
              onClick={() => downloadImage(image._id, image.url)}
              className="text-light-grey font-semibold px-5 py-2 rounded-full hover:bg-neon-pink hover:text-dark-blue"
            >
              <ArrowDownTrayIcon className="h-5 w-5 me-1 text-light-grey hover:text-dark-blue font-semibold inline-flex" />{" "}
              Download
            </button>
          </div>
        </div>
      </div>
    </Modal>
  );
};

export default ModalImageDetail;
