import React from "react";
import image4 from "../assets/image4.png";
import { ArrowDownTrayIcon } from "@heroicons/react/24/solid";

const ImagePage = () => {
  return (
    <div className="flex items-center justify-center h-screen bg-dark-blue">
      <div className="flex w-2/3 bg-dark-blue px-4 rounded-lg">
        {/* Left Side */}
        <div className="w-1/2 pr-6">
          <img
            src={image4}
            alt="AI Generated Image"
            className="w-full rounded-md"
          />
        </div>

        {/* Right Side */}
        <div className="w-1/2 pl-8">
          <h2 className=" text-light-grey mt-12 mb-4">
            Generated by: <span className="font-bold">Username</span>
          </h2>
          <div className="font-extrabold text-5xl text-light-grey  mb-6">
            <h1>Image Title</h1>
          </div>

          <p className=" text-light-grey font-bold">Prompt used: </p>
          <p className="text-light-grey">
            Realistic female android robot, cyberpunk, abstract, dramatic
            lighting, blue metallic colour, fine details, metallic parts
            showing.{" "}
          </p>
          <div className="mt-12">
            <p className="bg-medium-grey text-light-grey font-semibold px-5 py-2 rounded-full mr-6 inline-flex">
              Likes:<span className="likesNumber ml-1">100</span>
            </p>
            <button className="text-light-grey font-semibold hover:text-neon-pink ">
              <ArrowDownTrayIcon className="h-5 w-5 text-light-grey font-semibold  inline-flex" />{" "}
              Download
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};

export default ImagePage;
